### ISSUE TITLE
Env specific alias post failing in the production

### ISSUE THREAD

**Issue by brijpandey7519** [dxatscale/dxatscale#3]
Post sfpowerscripts version update deployment failing for env specific alias post package in the production:
sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:13.6.16 -Release:May 22.

Error from CI/CD pipelines:

----------------------------------Installing Package---------------------------------------------
Name: src-env-specific-alias-post
Type: source
Version Number: 18.0.0.493640099
Aliasified Package: True
Contains Apex Classes/Triggers: false
Always Deploy: True
-------------------------------------------------------------------------------------------------
Using alias directory default
Error: Aliasfied package 'src-env-specific-alias-post' does not have an alias with 'devhub'' or 'default' directory
----------------------------------------------------------------------------------------------------

**Comment by azlam-abdulsalam** [comment]
Please log the issue to sfpowerscripts repository
